- name: Installing Apache MSI 
  hosts: all 
 
  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.5.2/npp.8.5.2.Installer.x64.exe
        dest: C:\npp.8.5.2.Installer.x64.exe

    - name: Install MSI
      win_package: 
        path: C:\npp.8.5.2.Installer.x64.exe
        state: present
