---
- name: "Chocolatey"
  hosts: all
  tasks:
    - name: Ensure Chocolatey installed from internal repo
  win_chocolatey:
    name: chocolatey
    state: present
    source: https://github.com/himanshu-dhawan/ping.git/ChocolateyInstall.ps1
