---
- name: Install default apps
  hosts: all
  gather_facts: true
  tasks:
    - name: Install firefox
  win_chocolatey:
    name: firefox
    source: https://github.com/himanshu-dhawan/ping
    state: present
